In [1]:
import numpy as np
import math

An matrix example:

In [2]:
A = np.array([[1,-1,0.1],
              [2,-2,0.2]]) # 2x3 matrix
print(A.shape)

(2, 3)


Their tranponse:

In [3]:
AT = A.T
print(AT)
print("\n", AT.shape)

[[ 1.   2. ]
 [-1.  -2. ]
 [ 0.1  0.2]]

 (3, 2)


Now, I add a 2x4 matrix

In [4]:
W = np.array([[3,5,7,9],
              [4,6,8,0]])
print(W.shape)

(2, 4)


The purpose of this Notebook is to see how fast the matrix multiplication is done with vectorization, using NumPy matmul function `np.matmul(A,W)`

In [5]:
%%timeit -n1
Z = np.matmul(AT,W)
print(Z)
print("\n", Z.shape)


[[ 11.   17.   23.    9. ]
 [-11.  -17.  -23.   -9. ]
 [  1.1   1.7   2.3   0.9]]

 (3, 4)
[[ 11.   17.   23.    9. ]
 [-11.  -17.  -23.   -9. ]
 [  1.1   1.7   2.3   0.9]]

 (3, 4)
[[ 11.   17.   23.    9. ]
 [-11.  -17.  -23.   -9. ]
 [  1.1   1.7   2.3   0.9]]

 (3, 4)
[[ 11.   17.   23.    9. ]
 [-11.  -17.  -23.   -9. ]
 [  1.1   1.7   2.3   0.9]]

 (3, 4)
[[ 11.   17.   23.    9. ]
 [-11.  -17.  -23.   -9. ]
 [  1.1   1.7   2.3   0.9]]

 (3, 4)
[[ 11.   17.   23.    9. ]
 [-11.  -17.  -23.   -9. ]
 [  1.1   1.7   2.3   0.9]]

 (3, 4)
[[ 11.   17.   23.    9. ]
 [-11.  -17.  -23.   -9. ]
 [  1.1   1.7   2.3   0.9]]

 (3, 4)
The slowest run took 5.12 times longer than the fastest. This could mean that an intermediate result is being cached.
121 μs ± 87.9 μs per loop (mean ± std. dev. of 7 runs, 1 loop each)


Or alternative, using @:

In [6]:
%%timeit -n1
Z1 = AT @ W
print(Z1)

[[ 11.   17.   23.    9. ]
 [-11.  -17.  -23.   -9. ]
 [  1.1   1.7   2.3   0.9]]
[[ 11.   17.   23.    9. ]
 [-11.  -17.  -23.   -9. ]
 [  1.1   1.7   2.3   0.9]]
[[ 11.   17.   23.    9. ]
 [-11.  -17.  -23.   -9. ]
 [  1.1   1.7   2.3   0.9]]
[[ 11.   17.   23.    9. ]
 [-11.  -17.  -23.   -9. ]
 [  1.1   1.7   2.3   0.9]]
[[ 11.   17.   23.    9. ]
 [-11.  -17.  -23.   -9. ]
 [  1.1   1.7   2.3   0.9]]
[[ 11.   17.   23.    9. ]
 [-11.  -17.  -23.   -9. ]
 [  1.1   1.7   2.3   0.9]]
[[ 11.   17.   23.    9. ]
 [-11.  -17.  -23.   -9. ]
 [  1.1   1.7   2.3   0.9]]
The slowest run took 5.80 times longer than the fastest. This could mean that an intermediate result is being cached.
98.3 μs ± 84.1 μs per loop (mean ± std. dev. of 7 runs, 1 loop each)


I am going to take the previous data in the Coffee Roasting exercise

In [7]:
Coffee = np.array([[200, 17]])
Coffee.shape

(1, 2)

In [8]:
CoffeeT = Coffee.T
CoffeeT.shape

(2, 1)

In [9]:
W_Coffee = np.array([[1,-3,5],
                     [-2,4,-6]])
B_Coffee = np.array([[-1,1,2]])

print(W_Coffee.shape)
print(B_Coffee.shape)

(2, 3)
(1, 3)


In [10]:
def sigmoid(z):
    """"
    Compute the sigmoid of z

    Parameters:
    z : array_like -> A scalar or numpy array of any size

    Returns:
    g : array_like -> sigmoid(z)
    """

    z = np.clip(z, -500, 500) # protect against overflow -> np.clip: limit the values in an array
    g = 1.0/(1.0 + np.exp(-z))

    return g

In [11]:
def dense(AT, W, b):
    z = np.matmul(AT, W) + b
    a_out = g(z)
    return a_out

In [18]:
g = sigmoid
predictions = dense(Coffee, W_Coffee, B_Coffee)
predictions

array([[1.00000000e+000, 7.12457641e-218, 1.00000000e+000]])

In [20]:
yhat = (predictions >= 0.5).astype(int)
yhat

array([[1, 0, 1]])