In [2]:
import copy, math
import numpy as np
import matplotlib.pyplot as plt

In [3]:
#Data
X_train = np.array([[2104, 5, 1, 45], [1416, 3, 2, 40], [852, 2, 1, 35]])
Y_train = np.array([460, 232, 178])

In [4]:
#Data stored
print(f"X_Shape: {X_train.shape}, X Type:{type(X_train)}")
print(X_train)
print(f"Y_Shape: {Y_train.shape}, X Type:{type(Y_train)}")
print(Y_train)

X_Shape: (3, 4), X Type:<class 'numpy.ndarray'>
[[2104    5    1   45]
 [1416    3    2   40]
 [ 852    2    1   35]]
Y_Shape: (3,), X Type:<class 'numpy.ndarray'>
[460 232 178]


In [6]:
#Initial Parameters
b_init = 785.18
w_init = np.array([0.39, 18.75, -53.36, -26.42])
print(f"w_init Shape: {w_init.shape}, b_init type: {type(b_init)}")

w_init Shape: (4,), b_init type: <class 'float'>


In [10]:
def predict_single_loop(x, w, b):
    """
    single predict using linear regression

    Args:
        x (ndarray): Shape (n,) example with multiple features
        y (ndarray): Shape (n,) model parameters
        b (scalar): model parameter

    Returns: 
        p (scalar): prediction
    """

    n = x.shape[0]
    p = 0
    for i in range(n):
        p_i = x[i] * w[i]
        p = p + p_i
    p = p + b
    return p

In [11]:
#get a row from our training data
x_vect = X_train[0,:]
print(f"x_vect Shape: {x_vect.shape}, x_vect value: {x_vect}")

#make a prediction
f_wb = predict_single_loop(x_vect, w_init, b_init)
print(f"f_wb Shape: {f_wb.shape}, prediction: {f_wb}")

x_vect Shape: (4,), x_vect value: [2104    5    1   45]
f_wb Shape: (), prediction: 457.2299999999999
