In [1]:
import numpy as np
import time

In [4]:
#Numpy Broadcasting

#Numpy will have a fisrt parameter which is the shape of the object

#Numpy routines which allocate memory and fill arrays with value
a = np.zeros(4); print(f"np.zeros(4) : a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.zeros((4,)); print(f"np.zeros(4,) : a = {a}, a shpae = {a.shape}, a data type = {a.dtype}")
a = np.random.random_sample(4); print(f"np.random.random_sample(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.zeros(4) : a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.zeros(4,) : a = [0. 0. 0. 0.], a shpae = (4,), a data type = float64
np.random.random_sample(4): a = [0.9089928  0.20629781 0.67152174 0.85726035], a shape = (4,), a data type = float64


In [5]:
#NumPy routines which allocate memory and fill with user specified values

a = np.array([5,4,3,2]); print(f"np.array([5,4,3,2]): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.array([5.,4,3,2]); print(f"np.array([5.,4,3,2]) a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.array([5,4,3,2]): a = [5 4 3 2], a shape = (4,), a data type = int64
np.array([5.,4,3,2]) a = [5. 4. 3. 2.], a shape = (4,), a data type = float64


In [7]:
#Some data creation routines do not take a shape tuple
a = np.arange(4.); print(f"np.arange(4.): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.random.rand(4); print(f"no.random.rand(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.arange(4.): a = [0. 1. 2. 3.], a shape = (4,), a data type = float64
no.random.rand(4): a = [0.0919637  0.57977585 0.08573423 0.03896388], a shape = (4,), a data type = float64


In [15]:
### Operations on Vectors
# Indexing

#Vector indexing operations
x = np.arange(10)
print(x)

#access an element
print(f"a[2].shape: {x[2].shape} a[2] = {x[2]}, accesing an element returns a scalar")

#access the last element, negative indexes count from the end
print(f"a[-1] = {x[-1]}")

#indexs must be within the range of the vector or they will produce and error
try:
    c = x[10]
except Exception as e:
    print("The error message you'll see is:")
    print(e)


[0 1 2 3 4 5 6 7 8 9]
a[2].shape: () a[2] = 2, accesing an element returns a scalar
a[-1] = 9
The error message you'll see is:
index 10 is out of bounds for axis 0 with size 10


In [20]:
#Slicing
#Vector slicng operations
a = np.arange(10)
print("a = {a}")

#access 5 consecutive elements (start:stop:step)
c = a[2:7:1]; print("a[2:7:1] = ", c)

#access 3 elements separated by two
d = a[2:7:2]; print("a[2:7:2] = ", d)

#access all elements index 3 and above
f = a[3:]; print("a[3:] = ", f)

#access all elements below index 3
g = a[:3]; print("a[:3] = ", g)

#access all elements
h = a[:]; print("a[:] = ", h)


a = {a}
a[2:7:1] =  [2 3 4 5 6]
a[2:7:2] =  [2 4 6]
a[3:] =  [3 4 5 6 7 8 9]
a[:3] =  [0 1 2]
a[:] =  [0 1 2 3 4 5 6 7 8 9]


In [27]:
#Single vector operations

a = np.array([1,2,3,4])
print(f"a : {a}")

#negate all elements
b = - a
print(f"b:  {b}")

#Sum of all elements

c = np.sum(a)
print(f"Sum : {c}")

#mean

d = np.mean(a)
print(f"mean of c: {d}")

#Square
e = a ** 2
print(f"Square of a: {e}")

a : [1 2 3 4]
b:  [-1 -2 -3 -4]
Sum : 10
mean of c: 2.5
Square of a: [ 1  4  9 16]


In [29]:
#Operations with NumPy

a = np.array([1,2,3,4])
b = np.array([-1,-2,-3,-4])

print(a)
print(b)
print(f"Binary operators work element wis: {a+b}")

#Note: Vectors must be of the same size 

[1 2 3 4]
[-1 -2 -3 -4]
Binary operators work element wis: [0 0 0 0]


In [31]:
#Trying a mismatched vector operation
c = ([1,2])

try:
    d = a + c 
except Exception as e:
    print("The error message you'll see is: ")
    print(e)


The error message you'll see is: 
operands could not be broadcast together with shapes (4,) (2,) 


In [33]:
#Scalar vector operations

a = np.array([1,2,3,4,5,6])

#multiply for a scalar

b = 5 * a
print(f"b = 5 * a : {b}")



b = 5 * a : [ 5 10 15 20 25 30]


In [42]:
#Vector dot product


#Dot product using a loop

def dot(x, y):
    """"
    Compute the dot product of two vectors

    Args:
        x (ndarray(n,)): Input vector
        y (ndarray(n,)) : Input vector (same dimension as x)

    Retunrs:
        z (scalar):
    """
    n = x.shape[0]
    z = 0
    for i in range(n):
        z = z + x[i] * y[i]
    return z


In [43]:
#test 1-D
l = np.array([1,2,3,4,5,6,7,8,9,10])
m = np.array([2,4,6,8,10,12,14,16,18,20])

print(f"The vector dot operation using my function is: {dot(l,m)}")

The vector dot operation using my function is: 770


In [45]:
#Using np.dot


print(f"The vector dot operation using the preload NumPy dot function is: {np.dot(l,m)}")
print(f"The shape is: {np.dot(l,m).shape}")

The vector dot operation using the preload NumPy dot function is: 770
The shape is: ()


In [61]:
#Speed: Vector vs Loop
np.random.seed(1)
a = np.random.rand(100000000) #Very large arrays
b = np.random.rand(100000000)

tic = time.time() #capture start time
c = np.dot(a, b)
toc = time.time() #capture end time

Vect = toc - tic

print(f"np.dot(a, b): {c:.4f}")
print(f"Vectorized version duration: {(toc - tic):.4f} ms")

tic = time.time() #start time
d = dot(a,b)
toc = time.time() #end time

Loop = toc - tic

print(f"Loop version of dot product (a, b):{d:.4f} ")
print(f"Loop version duration: {(toc - tic):.4f} ms")

print("\n Loop version is:", (Loop/Vect)*100 ,   "% longer than Vectorized version")

del(a); del(b) #Delete these big arrays from memory

np.dot(a, b): 25000669.8073
Vectorized version duration: 0.0500 ms
Loop version of dot product (a, b):25000669.8073 
Loop version duration: 11.8357 ms

 Loop version is: 23664.846930506163 % longer than Vectorized version


In [65]:
#Example
X =np.array ([[1], [2], [3], [4]])
w = np.array([2])
c = np.dot(X[1], w)

print(f"X[1] has shape {X[1].shape}")
print(f"w has shape {w.shape}")
print(f"c has shape {c.shape}")

X[1] has shape (1,)
w has shape (1,)
c has shape ()


In [67]:
#Matrix Creation
a = np.zeros((1,5))
print(f"a shape = {a.shape}, a = {a}")

a = np.zeros((2,1))
print(f"a shape = {a.shape}, a = {a}")

a = np.random.random_sample((1,1))
print(f"a shape = {a.shape}, a = {a}")

a shape = (1, 5), a = [[0. 0. 0. 0. 0.]]
a shape = (2, 1), a = [[0.]
 [0.]]
a shape = (1, 1), a = [[0.8582913]]


In [2]:
a = np.array([[5],[4],[3]]); print(f"a shape = {a.shape}, np.array: a = {a}")
a = np.array([[5], #One can also
              [4], #Separate values
              [3]]) #into separate rows
print(f"a shape = {a.shape}, np.array: a = {a}")

a shape = (3, 1), np.array: a = [[5]
 [4]
 [3]]
a shape = (3, 1), np.array: a = [[5]
 [4]
 [3]]


In [11]:
#Operations on Matrices

#Indexing
#Vector indexing operations on Matrices
a = np.arange(6).reshape(-1,2) #reshape is a convinient  way to create matrices
print(f"a.shape: {a.shape}, \na= {a}")

#access an element
print(f"\na[2,0].shape: {a[2,0].shape}, a[2,0] = {a[2,0]}, type(a[2,0]) = {type(a[2,0])} Accesing an element returns a scalar\n")

#acces a row
print(f"a[2].shape: {a[2].shape}, a[2] = {a[2]}, type(a[2]) = {type(a[2])}")

a.shape: (3, 2), 
a= [[0 1]
 [2 3]
 [4 5]]

a[2,0].shape: (), a[2,0] = 4, type(a[2,0]) = <class 'numpy.int64'> Accesing an element returns a scalar

a[2].shape: (2,), a[2] = [4 5], type(a[2]) = <class 'numpy.ndarray'>


In [18]:
#Slicing
#vector 2-D slicing operations
a = np.arange(20).reshape(-1,10)
print(f"a = \n{a}")

#access  5 consecutive  elements (start:stop:step)
print("a[0, 2:7:1] = ", a[0, 2:7:1], ", a[0, 2:7:1].shape = ", a[0, 2:7:1].shape, "a 1-D array")

#acces 5 consecutive elements (start:stop:step) in two rows
print("a[:, 2:7:1] = \n", a[:, 2:7:1], ", a[:, 2:7:1].shape = ", a[:, 2:7:1].shape, "a 2-D array")

#access all elements 
print("a[:,:] = \n", a[:,:], ", a[:,:].shape =", a[:,:].shape)

#acces all elements in one row
print("a[1,:] = ", a[1,:], ", a[1,:].shape = ", a[1,:].shape, "a 1-D array")

#same as
print("a[1] = ", a[1], ", a[1].shape = ", a[1].shape, "a 1-D array")

a = 
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
a[0, 2:7:1] =  [2 3 4 5 6] , a[0, 2:7:1].shape =  (5,) a 1-D array
a[:, 2:7:1] = 
 [[ 2  3  4  5  6]
 [12 13 14 15 16]] , a[:, 2:7:1].shape =  (2, 5) a 2-D array
a[:,:] = 
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]] , a[:,:].shape = (2, 10)
a[1,:] =  [10 11 12 13 14 15 16 17 18 19] , a[1,:].shape =  (10,) a 1-D array
a[1] =  [10 11 12 13 14 15 16 17 18 19] , a[1].shape =  (10,) a 1-D array
